import type { Metadata } from "next";
import { Jockey_One } from "next/font/google";
import "./globals.css";

const jockey_One = Jockey_One({
	weight: ["400"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${jockey_One.className}  antialiased`}>{children}</body>
		</html>
	);
}
